name: CI

on:
  pull_request:
    branches:
      - dev
      - QA
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  #

    - name: Create .env file with GitHub Secrets
      run: |
        touch .env
        echo BASE_DE_DATOS=${{ secrets.BASE_DE_DATOS }} >> .env
        echo TOKEN=${{ secrets.TOKEN }} >> .env
        cat .env.production

    - name: Install dependencies
      run: npm install


    - name: Run tests
      run: npm test

    
